import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import MobileNavbar from "./components/MobileNavbar";
import Footer from "./components/Footer";

const inter = Poppins({
	subsets: ["latin"],
	weight: ["200", "300", "400", "600", "800"],
});

export const metadata: Metadata = {
	title: "Izrada Web Sajtova | Next Level | Web Design ",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${inter.className} bg-gray-950  min-h-screen relative  `}
			>
				<main className="max-w-screen-2xl mx-auto">
					<Navbar />
					{children}
					<Footer />
				</main>
			</body>
		</html>
	);
}
